Repository etalab/transport-site, pull requests merged in 2018-02, with the labels that each got.

#211 Publish reuse button is now readable
  client/stylesheets/base/_buttons.scss
  lib/transport_web/templates/dataset/details.html.eex
Labels: flow:in-progress, work:solution

#214 Fetch logo at organization.logo_thumbnail
  lib/transport/import_data_service.ex
Labels: flow:in-progress, work:bug

#217 Fix speling mistake
  priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
Labels: flow:in-progress, work:bug

#208 Do not display territory badge when there is no territory
  lib/transport_web/templates/dataset/details.html.eex
  lib/transport_web/templates/dataset/index.html.eex
  priv/gettext/en/LC_MESSAGES/page-dataset-details.po
  priv/gettext/en/LC_MESSAGES/page-shortlist.po
  priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
  priv/gettext/fr/LC_MESSAGES/page-shortlist.po
  priv/gettext/page-dataset-details.pot
  priv/gettext/page-shortlist.pot
Labels: flow:in-progress, work:bug

#207 Fix responsivity on dataset details page
  client/stylesheets/components/_dataset-details.scss
  client/stylesheets/components/_documentation.scss
  lib/transport_web/templates/dataset/details.html.eex
Labels: flow:in-progress, work:bug

#216 Add "Fichier" in possible CSV headers for udata
  lib/transport/import_data_service.ex
Labels: flow:in-progress, work:bug

#219 Compile language files
  priv/gettext/en/LC_MESSAGES/page-dataset-details.po
  priv/gettext/en/LC_MESSAGES/page-shortlist.po
  priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
  priv/gettext/fr/LC_MESSAGES/page-shortlist.po
  priv/gettext/page-dataset-details.pot
  priv/gettext/page-shortlist.pot
Labels: flow:in-progress, work:task

#218 Update curated list of datasets
  lib/mix/tasks/transport/import_data.ex
  lib/transport/import_data_service.ex
  lib/transport/reusable_data/reusable_data.ex
  priv/repo/datasets.json
Labels: flow:in-progress, work:task

#220 Fix json view
  lib/transport_web/api/views/dataset_view.ex
  lib/transport_web/api/views/json_view.ex
  lib/transport_web/router.ex
  priv/gettext/alert.pot
  priv/gettext/en/LC_MESSAGES/alert.po
  priv/gettext/fr/LC_MESSAGES/alert.po
Labels: flow:in-progress

#221 Fix subscribe datasets
  lib/transport_web/templates/dataset/details.html.eex
Labels: flow:in-progress

#222 Fix validation buttons style
  client/stylesheets/components/_validation.scss
Labels: flow:in-progress, work:bug

#233 Add compatibility with new datagouv API
  lib/transport/datagouvfr/client/datasets.ex
  priv/gettext/dataset.pot
  priv/gettext/en/LC_MESSAGES/dataset.po
  priv/gettext/fr/LC_MESSAGES/dataset.po
  test/fixture/cassettes/client/datasets/organization-datasets-6.json
  test/transport/datagouvfr/client/datasets_test.exs
Labels: flow:in-progress, work:bug

#204 Unroll help message when the mouse is over the help button
  client/javascripts/components/footer/footer-help.tag
  client/stylesheets/components/_footer-help.scss
  lib/transport_web/templates/layout/_footer.html.eex
  priv/gettext/default.pot
  priv/gettext/en/LC_MESSAGES/default.po
  priv/gettext/fr/LC_MESSAGES/default.po
  test/transport_web/integrations/contact_test.exs
Labels: flow:in-progress, work:improvement

#234 Fix text clause
  lib/transport_web/templates/dataset/details.html.eex
Labels: flow:in-progress

#236 Center the map on France by default
  client/javascripts/components/map/map.js
Labels: flow:in-progress
