Repository etalab/transport-site, pull requests merged in 2018-05, with the labels that each got.

#306 OSM data is under ODbL, not CC-BY-SA
  client/javascripts/components/map/map.js
Labels: flow:in-progress

#307 Rework home
  Dockerfile
  client/fonts/Evolventa/Evolventa-Bold.ttf
  client/fonts/Evolventa/Evolventa-BoldOblique.ttf
  client/fonts/Evolventa/Evolventa-Oblique.ttf
  client/fonts/Evolventa/Evolventa-Regular.ttf
  client/fonts/Evolventa/gpl.txt
  client/fonts/Evolventa/lppl.txt
  client/fonts/Source Sans Pro/SIL Open Font License.txt
  client/fonts/Source Sans Pro/SourceSansPro-Black.otf
  client/fonts/Source Sans Pro/SourceSansPro-BlackIt.otf
  client/fonts/Source Sans Pro/SourceSansPro-Bold.otf
  client/fonts/Source Sans Pro/SourceSansPro-BoldIt.otf
  client/fonts/Source Sans Pro/SourceSansPro-ExtraLight.otf
  client/fonts/Source Sans Pro/SourceSansPro-ExtraLightIt.otf
  client/fonts/Source Sans Pro/SourceSansPro-It.otf
  client/fonts/Source Sans Pro/SourceSansPro-Light.otf
  client/fonts/Source Sans Pro/SourceSansPro-LightIt.otf
  client/fonts/Source Sans Pro/SourceSansPro-Regular.otf
  client/fonts/Source Sans Pro/SourceSansPro-Semibold.otf
  client/fonts/Source Sans Pro/SourceSansPro-SemiboldIt.otf
  client/images/icons/arrow-down.svg
  client/images/icons/arrow-right.svg
  client/images/icons/tick.svg
  client/images/logo-header.svg
  client/images/tick.svg
  client/stylesheets/app.scss
  client/stylesheets/base/_buttons.scss
  client/stylesheets/base/_typography.scss
  client/stylesheets/components/_buttons.scss
  client/stylesheets/components/_header.scss
  client/stylesheets/components/_hero.scss
  client/stylesheets/components/_icons.scss
  client/stylesheets/components/_mailing-list.scss
  client/stylesheets/globals/_fonts.scss
  client/stylesheets/layouts/_header.scss
  client/stylesheets/layouts/_main.scss
  client/stylesheets/template.scss
  lib/transport_web/endpoint.ex
  lib/transport_web/templates/dataset/index.html.eex
  lib/transport_web/templates/layout/_header.html.eex
  lib/transport_web/templates/page/index.html.eex
  lib/transport_web/templates/page/login.html.eex
  priv/gettext/default.pot
  priv/gettext/en/LC_MESSAGES/default.po
  priv/gettext/en/LC_MESSAGES/page-index.po
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/fr/LC_MESSAGES/page-index.po
  priv/gettext/page-index.pot
  priv/static/documents/20180320_TransportDataGouv.pdf
  test/transport_web/integrations/login_test.exs
Labels: flow:in-progress

#309 Disable map test
  test/transport_web/solutions/data_reuse/using_map_test.exs
Labels: work:bug

#310 Present validation results in front
  lib/transport/reusable_data/dataset.ex
  lib/transport/reusable_data/reusable_data.ex
  lib/transport_web/templates/dataset/details.html.eex
  priv/gettext/en/LC_MESSAGES/page-dataset-details.po
  priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
  priv/gettext/page-dataset-details.pot
Labels: work:improvement

#304 Use a single task for importing the data
  README.md
  lib/mix/tasks/transport/reset_and_import.ex
Labels: flow:in-progress, work:improvement
