Repository etalab/transport-site, pull requests merged in 2018-03, with the labels that each got.

#237 Show username
  client/stylesheets/components/_header.scss
  lib/transport/datagouvfr/client/user.ex
  lib/transport_web/controllers/session_controller.ex
  lib/transport_web/templates/layout/_header.html.eex
  priv/gettext/default.pot
  test/transport_web/views/avatar_view_test.exs
Labels: work:improvement

#242 Update GTFS Angers and Royan + AOM in Open License
  priv/repo/datasets.json
Labels: flow:in-progress, work:task

#243 Fix mix task order
  README.md
Labels: flow:in-progress, work:documentation

#246 Update Phoenix framework
  mix.lock
Labels: flow:in-progress, work:task

#249 Fix changed slug of STAN network (Nancy)
  priv/repo/datasets.json
Labels: flow:in-progress, work:bug

#252 Import data on deploy
  .circleci/config.yml
  lib/transport/import_data_service.ex
Labels: flow:in-progress, work:improvement

#254 Fix IRIGO and Transpole
  priv/repo/datasets.json
Labels: flow:in-progress, work:bug

#256 Improve import data task logs
  lib/transport/import_data_service.ex
Labels: flow:in-progress, work:improvement

#253 Check external links on CircleCI before deployment
  .circleci/config.yml
  README.md
  config/datagouvfr.exs
  config/test.exs
  lib/transport/import_data_service.ex
  lib/transport/reusable_data/dataset.ex
  priv/repo/datasets.json
  test/test_helper.exs
  test/transport/import_data_service_test.exs
Labels: flow:in-progress, work:improvement

#258 Fix import of cara'bus network
  lib/transport/import_data_service.ex
  priv/repo/datasets.json
Labels: flow:in-progress, work:bug

#257 Log when dataset download uri not found
  lib/transport/import_data_service.ex
Labels: flow:in-progress, work:improvement

#244 Validate with datatools
  README.md
  lib/mix/tasks/transport/fetch_validation_results.ex
  lib/mix/tasks/transport/validate_data.ex
  lib/transport/data_validation/aggregates/feed_source.ex
  lib/transport/data_validation/aggregates/feed_version.ex
  lib/transport/data_validation/aggregates/project.ex
  lib/transport/data_validation/data_validation.ex
  lib/transport/data_validation/queries/find_feed_version.ex
  lib/transport/data_validation/queries/list_feed_sources.ex
  lib/transport/data_validation/repository/feed_source_repository.ex
  lib/transport/data_validation/repository/feed_version_repository.ex
  lib/transport/datagouvfr/client.ex
  priv/repo/datasets.json
  test/fixture/cassettes/data_validation/find_feed_version-ok.json
  test/fixture/cassettes/data_validation/list_feed_sources-ok.json
  test/transport/data_validation/data_validation_test.exs
  test/transport/data_validation/queries/find_feed_source_version.exs
  test/transport/data_validation/queries/list_feed_sources_test.exs
Labels: flow:in-progress

#261 Add project repository tests
  test/fixture/cassettes/data_validation/find_project-not_found.json
  test/transport/data_validation/aggregates/project_test.exs
  test/transport/data_validation/repository/project_repository_test.exs
Labels: flow:in-progress, work:improvement

#262 Fix an html typo
  lib/transport_web/templates/dataset/details.html.eex
Labels: flow:in-progress, work:improvement

#238 Remove Google's gtfs-validator integration
  .circleci/Dockerfile
  .circleci/config.yml
  .envrc.example
  app.json
  client/javascripts/components/validation/validation.tag
  config/amqp.exs
  config/config.exs
  lib/mix/tasks/transport/reset.ex
  lib/transport/application.ex
  lib/transport/data_validator/celery_task.ex
  lib/transport/data_validator/server.ex
  lib/transport/reusable_data/dataset.ex
  lib/transport/validation/validation.ex
  lib/transport_web/controllers/user_controller.ex
  mix.exs
  mix.lock
  priv/gettext/en/LC_MESSAGES/default.po
  priv/gettext/en/LC_MESSAGES/user.po
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/fr/LC_MESSAGES/user.po
  priv/gettext/user.pot
  test/transport/data_validator/celery_task_test.exs
  test/transport/data_validator/server_test.exs
  test/transport/reusable_data/reusable_data_test.exs
  test/transport_web/api/controllers/dataset_controller_test.exs
  test/transport_web/solutions/data_reuse/using_list_test.exs
  test/transport_web/solutions/data_reuse/using_map_test.exs
Labels: flow:in-progress, work:improvement

#263 Use dockerimage from betagouv profile
  .circleci/Dockerfile
  .circleci/config.yml
  README.md
Labels: flow:in-progress, work:ops

#268 Use https for catalogue
  client/javascripts/components/validation/catalogueerrors.tag
Labels: flow:in-progress, work:bug

#269 Add datasets
  priv/repo/datasets.json
Labels: flow:in-progress, work:task

#266 Translate the subscription button
  lib/transport_web/templates/page/index.html.eex
  priv/gettext/en/LC_MESSAGES/page-index.po
  priv/gettext/fr/LC_MESSAGES/page-index.po
  priv/gettext/page-index.pot
Labels: flow:in-progress, work:improvement

#265 Add link to connect to slack
  client/stylesheets/components/_mailing-list.scss
  lib/transport_web/templates/page/index.html.eex
  priv/gettext/en/LC_MESSAGES/page-index.po
  priv/gettext/fr/LC_MESSAGES/page-index.po
  priv/gettext/page-index.pot
Labels: flow:in-progress, work:solution

#267 Let CircleCI provide mongo and phantom for CI
  .circleci/config.yml
Labels: flow:in-progress, work:ops

#270 Bump transport docker version
  .circleci/config.yml
Labels: flow:in-progress, work:ops

#272 Add forgotten slack icon
  client/images/slack.png
Labels: flow:in-progress, work:bug

#271 Use CircleCI workflows
  .circleci/config.yml
  mix.exs
  mix.lock
Labels: flow:in-progress, work:ops

#273 Update CPUs
  lib/transport_web/templates/dataset/details.html.eex
  lib/transport_web/templates/user/organization_datasets.html.eex
Labels: flow:in-progress

#275 Fix faker start error
  mix.exs
Labels: flow:in-progress, work:bug
