Repository etalab/transport-site, pull requests merged in 2018-04, with the labels that each got.

#274 Add integration testing for data validation
  .circleci/config.yml
  lib/transport/data_validation/data_validation.ex
  lib/transport/data_validation/repository/feed_version_repository.ex
  test/transport/data_validation/data_validation_test.exs
Labels: flow:in-progress, work:improvement, work:ops

#283 Format the markdown in comments
  client/javascripts/components/discussions/discussions.tag
  client/stylesheets/components/_discussions.scss
Labels: flow:in-progress, work:improvement

#285 Deploy even if external tests fail
  .circleci/config.yml
Labels: flow:in-progress, work:task

#287 Skip dataset validation when no download URI found
  lib/mix/tasks/transport/validate_data.ex
  priv/gettext/en/LC_MESSAGES/validations.po
  priv/gettext/fr/LC_MESSAGES/validations.po
  priv/gettext/validations.pot
Labels: flow:in-progress, work:bug

#286 Fix deployment to heroku by Circle-Ci
  .circleci/config.yml
Labels: flow:in-progress, work:bug

#288 Fix heroku deploy
  .circleci/config.yml
  .circleci/setup-heroku.sh
Labels: flow:in-progress, work:bug

#284 Use french date and time formating
  client/javascripts/components/discussions/discussions.tag
Labels: flow:in-progress, work:improvement

#291 Add Saint Brieuc
  priv/repo/datasets.json
Labels: flow:in-progress, work:task

#293 Bump docker datatools 0.1.1
  .circleci/config.yml
Labels: flow:in-progress, work:ops

#295 Add Le Mans
  priv/repo/datasets.json
Labels: flow:in-progress

#297 Add Fougères
  priv/repo/datasets.json
Labels: flow:in-progress

#298 Add Strasbourg
  priv/repo/datasets.json
Labels: flow:in-progress

#299 Update MEL and Grenoble slugs
  priv/repo/datasets.json
Labels: flow:in-progress
