Repository etalab/transport-site, pull requests merged in 2024-12, with the labels that each got.

#4347 Mises à jour techniques relatives à Ecto
  apps/transport/mix.exs
  apps/transport/priv/repo/migrations/20221206135302_data_import_delete.exs
  mix.lock
  scripts/drop_and_recreate_database.exs
Labels: dette technique

#4367 Ajout changelog CleverCloud et + dans le README
  README.md
Labels: documentation

#4326 Validateur NeTEx : polling des résultats
  apps/transport/lib/jobs/netex_poller_job.ex
  apps/transport/lib/jobs/on_demand_netex_poller_job.ex
  apps/transport/lib/jobs/on_demand_validation_helpers.ex
  apps/transport/lib/jobs/on_demand_validation_job.ex
  apps/transport/lib/transport_web/controllers/resource_controller.ex
  apps/transport/lib/validators/netex_validator.ex
  apps/transport/lib/validators/validator_selection.ex
  apps/transport/test/support/enroute_chouette_valid_client_helpers.ex
  apps/transport/test/transport/jobs/netex_poller_job_test.exs
  apps/transport/test/transport/jobs/on_demand_netex_poller_job_test.exs
  apps/transport/test/transport/jobs/on_demand_validation_job_test.exs
  apps/transport/test/transport/validators/netex_validator_test.exs
  apps/transport/test/transport/validators/validator_selection_test.exs
  apps/transport/test/transport_web/controllers/resource_controller_test.exs
Labels: NeTEx

#4346 Travail sur la dette technique - compatibilité OTP 26+
  apps/transport/lib/transport_web/controllers/backoffice/contact_controller.ex
  apps/transport/lib/transport_web/controllers/dataset_controller.ex
  apps/transport/lib/transport_web/live/on_demand_validation_select_live.ex
  apps/transport/lib/transport_web/views/dataset_view.ex
  apps/transport/test/build_test.exs
  apps/transport/test/db/db_dataset_test.exs
  apps/transport/test/transport_web/controllers/backoffice/contact_controller_test.exs
Labels: dette technique

#4389 Correctif & amélioration outil de scan IRVE back-office
  apps/transport/lib/irve/extractor.ex
  apps/transport/lib/transport_web/live/backoffice/irve_dashboard_live.ex
  apps/transport/lib/transport_web/live/backoffice/irve_dashboard_live.html.heex
  apps/transport/test/transport/irve/irve_extractor_test.exs
Labels: IRVE

#4405 Hot-fix: shutdown du worker si les jobs ne sont plus traités
  apps/transport/lib/transport_web/plugs/worker_healthcheck.ex
Labels: ops
