Repository etalab/transport-site, pull requests merged in 2024-05, with the labels that each got.

#3919 Skip d'un test qui échoue sur Mac M1
  apps/transport/test/build_test.exs
  apps/transport/test/support/platform.ex
Labels: dette technique

#3916 Ajout page infos_reutilisateurs
  apps/transport/lib/transport_web/controllers/page_controller.ex
  apps/transport/lib/transport_web/router.ex
  apps/transport/lib/transport_web/templates/page/infos_reutilisateurs.html.heex
  apps/transport/priv/gettext/en/LC_MESSAGES/reuser-space.po
  apps/transport/priv/gettext/fr/LC_MESSAGES/reuser-space.po
  apps/transport/priv/gettext/reuser-space.pot
  apps/transport/test/transport_web/controllers/page_controller_test.exs
Labels: réutilisateurs

#3915 Espace producteur : redirection vers page info quand non connecté
  apps/transport/lib/transport_web/router.ex
  apps/transport/lib/transport_web/templates/page/infos_producteurs.html.heex
  apps/transport/test/transport_web/controllers/espace_producteur_controller_test.exs
  apps/transport/test/transport_web/controllers/page_controller_test.exs
  apps/transport/test/transport_web/live_views/notifications_live_test.exs
Labels: producteurs

#3918 Dataset#details : fonctionnement du coeur des favoris
  apps/transport/client/stylesheets/components/_dataset-details.scss
  apps/transport/client/stylesheets/components/_icons.scss
  apps/transport/client/stylesheets/components/_tooltip.scss
  apps/transport/lib/transport_web/live/follow_dataset_live.ex
  apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
  apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
  apps/transport/priv/gettext/page-dataset-details.pot
  apps/transport/test/transport_web/live_views/follow_dataset_live_test.exs
Labels: réutilisateurs

#3917 Résultats de recherche : affichage des coeurs de suivi
  apps/transport/client/stylesheets/components/_shortlist.scss
  apps/transport/lib/transport_web/controllers/dataset_controller.ex
  apps/transport/lib/transport_web/templates/dataset/index.html.heex
  apps/transport/lib/transport_web/views/dataset_view.ex
  apps/transport/test/transport_web/controllers/dataset_controller_test.exs
Labels: réutilisateurs

#3941 Ajout d'un Livebook pour comparer des fichiers IRVE
  scripts/irve_diff.livemd
Labels: IRVE

#3945 Test moins sensible au temps qui passe
  apps/transport/test/transport/jobs/warn_user_inactivity_job_test.exs
Labels: dette technique
